name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    - name: Install dependencies
      run: npm install
    - name: Create distribution build
      run: npm run package
    - name: Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: release-${{ github.sha }}
        path: dist
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: publish
      with:
        app-name: invoiceman
        package: './dist/'
    

