name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      env:
        CI: true
    - name: Install dependencies
      run: npm install
    - name: Create distribution build
      run: npm run package
    - uses: actions/upload-artifact@master
    - name: Upload artifact
      with:
        name: release-${{ github.sha }}
        path: dist
