name: Node CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Create artifact
      run: |
        npm install
        npm run package
      
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact

      env:
        CI: true
